# Send 24 colors to tmux instead of 256 bit
set -as terminal-features ",xterm-ghostty:RGB"

# Change prefix from Ctrl+b to Ctrl+a (Easier to reach)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Split panes using | and - (Much more intuitive)
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Standard vim-style pane selection (Prefix + h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Don't rename windows automatically (keeps things organized)
set-option -g allow-rename off

# 1-based indexing
set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

# QoL
set -g escape-time 0
set -g history-limit 10000

# Vim-style copy mode
setw -g mode-keys vi
bind [ copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel

# Mouse on
set -g mouse on

# Allow passthrough so base terminal can receive notificaitons.
set -g allow-passthrough on

# Allow extended-keys
set -as terminal-features 'xterm*:extkeys'
set -s extended-keys on
